### ISSUE TITLE
多表关联的时候有个BUG

### ISSUE THREAD

**Issue by keller31** [al-one/laravel-soft-deletes-unix#2]
return $this->hasManyThrough(
            Merchant::class,
            MerchantUser::class,
            'user_id', // 用户表外键
            'id', // 表外键
            'id', // 本地键
            'merchant_id' // 中间表 本地键
        );

select
  `xyb_merchant`.*,
  `xyb_merchant_user`.`user_id` as `laravel_through_key`
from
  `xyb_merchant`
  inner join `xyb_merchant_user` on `xyb_merchant_user`.`merchant_id` = `xyb_merchant`.`id`
where
 `xyb_merchant_user`.`deleted_at` is null
  and `xyb_merchant_user`.`user_id` = 6
  and (
    `xyb_merchant`.`deleted_at` = 0
    or `xyb_merchant`.`deleted_at` > 1564122113
  )

**Comment by keller31** [comment]
_xyb_merchant_user.deleted_at is null_

**Comment by al-one** [comment]
`v1.5.3-beta3+`已修复。
